<script setup lang="ts">
/**
 * This file was automatically generated by simpleapp everytime regenerate code.
 * delete file "delete-me-for-avoid-override" if you want to modify this file and
 * prevent regenerate code override it.
 * last change 2023-09-09
 * author: Ks Tan
 */
import ConfirmPopup from "primevue/confirmpopup";
import { useConfirm } from "primevue/useconfirm";
const confirm = useConfirm();

const { $BranchDoc, $OrganizationDoc, $event } = useNuxtApp();
const orgdoc = $OrganizationDoc();
const doc = $BranchDoc();
const data = doc.getReactiveData();
const bid = ref(String(useRoute().params.bid ?? ""));

const fetchRecord = async (id: string) => {
  await doc.getById(id);
};

const disabled = computed(() => {
  return false;
});

const createData = async () => {
  doc
    .create()
    .then((res) => {
      refresh();
      goBranch(res.data.organization._id, res.data._id);
    })
    .catch((err) => {
      console.error(err);
    });
};
const updateData = async () => {
  doc
    .update()
    .then(() => {
      // visible.value=false
      refresh();
    })
    .catch((err) => {
      console.error(err);
    });
};
const deleteData = (event: Event) => {
  confirm.require({
    target: event.currentTarget as HTMLElement,
    message: "Delete?",
    icon: "pi pi-exclamation-triangle",
    acceptClass: "p-button-danger",
    accept: () => {
      // disabled.value=true
      doc.delete(data.value._id ?? "").then((res) => {
        refresh();
        goTo(doc.getDocName());
      });
    },
    reject: () => {
      console.log("Cancel delete");
    },
  });
};

const refresh = () => {
  $event("RefreshDocumentList", { documentName: doc.getDocName() });
};

if (bid.value) {
  console.log("bid value", bid.value);
  fetchRecord(bid.value);
} else {
  const orgRecordid = ref(String(useRoute().params.id));
  const orgdata = (await orgdoc.getById(orgRecordid.value)).data;
  doc.setNew();
  data.value.tenantId = orgdata.tenantId;
  data.value.orgId = orgdata.orgId;
  data.value.organization._id = orgRecordid.value;
  data.value.organization.label = orgdata.orgName;
  data.value.organization.orgId = orgdata.orgId;
  data.value.organization.code = orgdata.orgCode;
}
</script>
<template>
  <div class="grid grid-cols2">
    <SimpleAppForm :document="doc" #default="o">
      <div class="simpleapp-tool-bar col-span-4 text-left gap-4">
        <!-- <Button
                class=""
                :disabled="disabled"
                @click="newData"
                type="button"
                v-if="canPerform(doc.getDocName(), 'create')"
                >New</Button
              > -->
        <Button
          class="btn btn-primary"
          :disabled="disabled"
          @click="createData"
          type="button"
          v-if="canPerform(doc.getDocName(), 'create') && doc.isNew()"
          >Create</Button
        >
        <Button
          class="btn btn-primary"
          :disabled="disabled"
          @click="updateData"
          type="button"
          v-if="canPerform(doc.getDocName(), 'update') && !doc.isNew()"
          >Update</Button
        >
        <Button
          class="btn btn-danger"
          :disabled="disabled"
          @click="deleteData($event)"
          type="button"
          v-if="canPerform(doc.getDocName(), 'delete') && !doc.isNew()"
          >Delete</Button
        >

        <ProgressSpinner
          v-if="disabled == true"
          style="width: 2rem; height: 2rem"
        ></ProgressSpinner>
        <ConfirmPopup></ConfirmPopup>
      </div>
      <SimpleAppText
        v-model="data.branchCode"
        :setting="o.getField('#/properties/branchCode')"
      />
      <SimpleAppText
        v-model="data.branchName"
        :setting="o.getField('#/properties/branchName')"
      />
      <SimpleAppCheckbox
        v-model="data.active"
        :setting="o.getField('#/properties/active')"
      />
      <SimpleAppTextarea
        v-model="data.description"
        :setting="o.getField('#/properties/description')"
      />      
    </SimpleAppForm>
    <DebugDocumentData v-model="data" label="branch" />
  </div>
</template>
