/**
 * This file was automatically generated by simpleapp generator. Every
 * MODIFICATION OVERRIDE BY GENERATEOR
 * last change 2023-10-28
 * Author: Ks Tan
 */
import { Injectable } from '@nestjs/common';
// import { Workflow } from './simpleapp/generate/commons/providers/Workflow';
@Injectable()
export class AppService {
  async getMyTask() {
    // return await Workflow.getInstance().getMyUserTask()
    return "ok"
  }
}
